[theme]
# Light theme configuration
primaryColor = "#667eea"           # Purple accent (matches your gradient)
backgroundColor = "#ffffff"        # White background
secondaryBackgroundColor = "#f8f9ff"  # Light purple-ish gray
textColor = "#1f2937"              # Dark gray text
font = "sans serif"                # Clean sans-serif font

# Optional: Base theme
base = "light"                     # Use light theme as base